import { MigrationInterface, QueryRunner } from "typeorm";

export class postRefactoring1655657430330 implements MigrationInterface {
    name = 'postRefactoring1655657430330'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "handle" varchar NOT NULL, "email" varchar NOT NULL, "password" varchar NOT NULL, "bio" varchar NOT NULL DEFAULT (''), "avatar" varchar NOT NULL DEFAULT (''), CONSTRAINT "UQ_6a7e5f591436179c411f5308a9e" UNIQUE ("handle"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"))`);
        await queryRunner.query(`CREATE TABLE "hashtags" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "text" varchar NOT NULL, CONSTRAINT "UQ_d8a87e5486a087a003c29228585" UNIQUE ("text"))`);
        await queryRunner.query(`CREATE TABLE "tweets" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "text" varchar(280) NOT NULL, "image" varchar NOT NULL DEFAULT (''), "commentAllowed" varchar NOT NULL DEFAULT ('everyone'), "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "author_id" integer NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "comments" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "text" varchar NOT NULL, "image" varchar NOT NULL DEFAULT (''), "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "author_id" integer NOT NULL, "tweet_id" integer NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "users_retweets_tweets" ("usersId" integer NOT NULL, "tweetsId" integer NOT NULL, PRIMARY KEY ("usersId", "tweetsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_73b033036fce7837ab92be3372" ON "users_retweets_tweets" ("usersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_61882bbc479c68d6d8e78cd4fc" ON "users_retweets_tweets" ("tweetsId") `);
        await queryRunner.query(`CREATE TABLE "users_followers_users" ("usersId_1" integer NOT NULL, "usersId_2" integer NOT NULL, PRIMARY KEY ("usersId_1", "usersId_2"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8d63f6043394b4d32343bdea11" ON "users_followers_users" ("usersId_1") `);
        await queryRunner.query(`CREATE INDEX "IDX_1433e3275a501bc09f5c33c7ca" ON "users_followers_users" ("usersId_2") `);
        await queryRunner.query(`CREATE TABLE "hashtags_tweets_tweets" ("hashtagsId" integer NOT NULL, "tweetsId" integer NOT NULL, PRIMARY KEY ("hashtagsId", "tweetsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_946e8168d267545ce143b93a31" ON "hashtags_tweets_tweets" ("hashtagsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b8bc26740590d4a2740a8c29e2" ON "hashtags_tweets_tweets" ("tweetsId") `);
        await queryRunner.query(`CREATE TABLE "tweets_favorited_by_users_users" ("tweetsId" integer NOT NULL, "usersId" integer NOT NULL, PRIMARY KEY ("tweetsId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a2b4a8e105439cac45a404c97c" ON "tweets_favorited_by_users_users" ("tweetsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e28f0beac1581abaefce32d51b" ON "tweets_favorited_by_users_users" ("usersId") `);
        await queryRunner.query(`CREATE TABLE "tweets_saved_by_users_users" ("tweetsId" integer NOT NULL, "usersId" integer NOT NULL, PRIMARY KEY ("tweetsId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_719f65dd281f090dc50af6d1de" ON "tweets_saved_by_users_users" ("tweetsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_92925b1bdd372ce994c9e94eb4" ON "tweets_saved_by_users_users" ("usersId") `);
        await queryRunner.query(`CREATE TABLE "comments_liked_by_users_users" ("commentsId" integer NOT NULL, "usersId" integer NOT NULL, PRIMARY KEY ("commentsId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d00c912f2d8aa0284a58425217" ON "comments_liked_by_users_users" ("commentsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_194ef33aa9b7f19efb9b1656a6" ON "comments_liked_by_users_users" ("usersId") `);
        await queryRunner.query(`CREATE TABLE "temporary_tweets" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "text" varchar(280) NOT NULL, "image" varchar NOT NULL DEFAULT (''), "commentAllowed" varchar NOT NULL DEFAULT ('everyone'), "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "author_id" integer NOT NULL, CONSTRAINT "FK_6783f8d04acbff7ce2b2ee823f7" FOREIGN KEY ("author_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE)`);
        await queryRunner.query(`INSERT INTO "temporary_tweets"("id", "text", "image", "commentAllowed", "created_at", "author_id") SELECT "id", "text", "image", "commentAllowed", "created_at", "author_id" FROM "tweets"`);
        await queryRunner.query(`DROP TABLE "tweets"`);
        await queryRunner.query(`ALTER TABLE "temporary_tweets" RENAME TO "tweets"`);
        await queryRunner.query(`CREATE TABLE "temporary_comments" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "text" varchar NOT NULL, "image" varchar NOT NULL DEFAULT (''), "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "author_id" integer NOT NULL, "tweet_id" integer NOT NULL, CONSTRAINT "FK_e6d38899c31997c45d128a8973b" FOREIGN KEY ("author_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_cdca270ba1f5105a09e64562fef" FOREIGN KEY ("tweet_id") REFERENCES "tweets" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_comments"("id", "text", "image", "created_at", "author_id", "tweet_id") SELECT "id", "text", "image", "created_at", "author_id", "tweet_id" FROM "comments"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`ALTER TABLE "temporary_comments" RENAME TO "comments"`);
        await queryRunner.query(`DROP INDEX "IDX_73b033036fce7837ab92be3372"`);
        await queryRunner.query(`DROP INDEX "IDX_61882bbc479c68d6d8e78cd4fc"`);
        await queryRunner.query(`CREATE TABLE "temporary_users_retweets_tweets" ("usersId" integer NOT NULL, "tweetsId" integer NOT NULL, CONSTRAINT "FK_73b033036fce7837ab92be33729" FOREIGN KEY ("usersId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_61882bbc479c68d6d8e78cd4fcb" FOREIGN KEY ("tweetsId") REFERENCES "tweets" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("usersId", "tweetsId"))`);
        await queryRunner.query(`INSERT INTO "temporary_users_retweets_tweets"("usersId", "tweetsId") SELECT "usersId", "tweetsId" FROM "users_retweets_tweets"`);
        await queryRunner.query(`DROP TABLE "users_retweets_tweets"`);
        await queryRunner.query(`ALTER TABLE "temporary_users_retweets_tweets" RENAME TO "users_retweets_tweets"`);
        await queryRunner.query(`CREATE INDEX "IDX_73b033036fce7837ab92be3372" ON "users_retweets_tweets" ("usersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_61882bbc479c68d6d8e78cd4fc" ON "users_retweets_tweets" ("tweetsId") `);
        await queryRunner.query(`DROP INDEX "IDX_8d63f6043394b4d32343bdea11"`);
        await queryRunner.query(`DROP INDEX "IDX_1433e3275a501bc09f5c33c7ca"`);
        await queryRunner.query(`CREATE TABLE "temporary_users_followers_users" ("usersId_1" integer NOT NULL, "usersId_2" integer NOT NULL, CONSTRAINT "FK_8d63f6043394b4d32343bdea11d" FOREIGN KEY ("usersId_1") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_1433e3275a501bc09f5c33c7ca2" FOREIGN KEY ("usersId_2") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("usersId_1", "usersId_2"))`);
        await queryRunner.query(`INSERT INTO "temporary_users_followers_users"("usersId_1", "usersId_2") SELECT "usersId_1", "usersId_2" FROM "users_followers_users"`);
        await queryRunner.query(`DROP TABLE "users_followers_users"`);
        await queryRunner.query(`ALTER TABLE "temporary_users_followers_users" RENAME TO "users_followers_users"`);
        await queryRunner.query(`CREATE INDEX "IDX_8d63f6043394b4d32343bdea11" ON "users_followers_users" ("usersId_1") `);
        await queryRunner.query(`CREATE INDEX "IDX_1433e3275a501bc09f5c33c7ca" ON "users_followers_users" ("usersId_2") `);
        await queryRunner.query(`DROP INDEX "IDX_946e8168d267545ce143b93a31"`);
        await queryRunner.query(`DROP INDEX "IDX_b8bc26740590d4a2740a8c29e2"`);
        await queryRunner.query(`CREATE TABLE "temporary_hashtags_tweets_tweets" ("hashtagsId" integer NOT NULL, "tweetsId" integer NOT NULL, CONSTRAINT "FK_946e8168d267545ce143b93a31d" FOREIGN KEY ("hashtagsId") REFERENCES "hashtags" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_b8bc26740590d4a2740a8c29e28" FOREIGN KEY ("tweetsId") REFERENCES "tweets" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("hashtagsId", "tweetsId"))`);
        await queryRunner.query(`INSERT INTO "temporary_hashtags_tweets_tweets"("hashtagsId", "tweetsId") SELECT "hashtagsId", "tweetsId" FROM "hashtags_tweets_tweets"`);
        await queryRunner.query(`DROP TABLE "hashtags_tweets_tweets"`);
        await queryRunner.query(`ALTER TABLE "temporary_hashtags_tweets_tweets" RENAME TO "hashtags_tweets_tweets"`);
        await queryRunner.query(`CREATE INDEX "IDX_946e8168d267545ce143b93a31" ON "hashtags_tweets_tweets" ("hashtagsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b8bc26740590d4a2740a8c29e2" ON "hashtags_tweets_tweets" ("tweetsId") `);
        await queryRunner.query(`DROP INDEX "IDX_a2b4a8e105439cac45a404c97c"`);
        await queryRunner.query(`DROP INDEX "IDX_e28f0beac1581abaefce32d51b"`);
        await queryRunner.query(`CREATE TABLE "temporary_tweets_favorited_by_users_users" ("tweetsId" integer NOT NULL, "usersId" integer NOT NULL, CONSTRAINT "FK_a2b4a8e105439cac45a404c97c3" FOREIGN KEY ("tweetsId") REFERENCES "tweets" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_e28f0beac1581abaefce32d51b0" FOREIGN KEY ("usersId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("tweetsId", "usersId"))`);
        await queryRunner.query(`INSERT INTO "temporary_tweets_favorited_by_users_users"("tweetsId", "usersId") SELECT "tweetsId", "usersId" FROM "tweets_favorited_by_users_users"`);
        await queryRunner.query(`DROP TABLE "tweets_favorited_by_users_users"`);
        await queryRunner.query(`ALTER TABLE "temporary_tweets_favorited_by_users_users" RENAME TO "tweets_favorited_by_users_users"`);
        await queryRunner.query(`CREATE INDEX "IDX_a2b4a8e105439cac45a404c97c" ON "tweets_favorited_by_users_users" ("tweetsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e28f0beac1581abaefce32d51b" ON "tweets_favorited_by_users_users" ("usersId") `);
        await queryRunner.query(`DROP INDEX "IDX_719f65dd281f090dc50af6d1de"`);
        await queryRunner.query(`DROP INDEX "IDX_92925b1bdd372ce994c9e94eb4"`);
        await queryRunner.query(`CREATE TABLE "temporary_tweets_saved_by_users_users" ("tweetsId" integer NOT NULL, "usersId" integer NOT NULL, CONSTRAINT "FK_719f65dd281f090dc50af6d1de1" FOREIGN KEY ("tweetsId") REFERENCES "tweets" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_92925b1bdd372ce994c9e94eb49" FOREIGN KEY ("usersId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("tweetsId", "usersId"))`);
        await queryRunner.query(`INSERT INTO "temporary_tweets_saved_by_users_users"("tweetsId", "usersId") SELECT "tweetsId", "usersId" FROM "tweets_saved_by_users_users"`);
        await queryRunner.query(`DROP TABLE "tweets_saved_by_users_users"`);
        await queryRunner.query(`ALTER TABLE "temporary_tweets_saved_by_users_users" RENAME TO "tweets_saved_by_users_users"`);
        await queryRunner.query(`CREATE INDEX "IDX_719f65dd281f090dc50af6d1de" ON "tweets_saved_by_users_users" ("tweetsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_92925b1bdd372ce994c9e94eb4" ON "tweets_saved_by_users_users" ("usersId") `);
        await queryRunner.query(`DROP INDEX "IDX_d00c912f2d8aa0284a58425217"`);
        await queryRunner.query(`DROP INDEX "IDX_194ef33aa9b7f19efb9b1656a6"`);
        await queryRunner.query(`CREATE TABLE "temporary_comments_liked_by_users_users" ("commentsId" integer NOT NULL, "usersId" integer NOT NULL, CONSTRAINT "FK_d00c912f2d8aa0284a58425217b" FOREIGN KEY ("commentsId") REFERENCES "comments" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_194ef33aa9b7f19efb9b1656a6d" FOREIGN KEY ("usersId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("commentsId", "usersId"))`);
        await queryRunner.query(`INSERT INTO "temporary_comments_liked_by_users_users"("commentsId", "usersId") SELECT "commentsId", "usersId" FROM "comments_liked_by_users_users"`);
        await queryRunner.query(`DROP TABLE "comments_liked_by_users_users"`);
        await queryRunner.query(`ALTER TABLE "temporary_comments_liked_by_users_users" RENAME TO "comments_liked_by_users_users"`);
        await queryRunner.query(`CREATE INDEX "IDX_d00c912f2d8aa0284a58425217" ON "comments_liked_by_users_users" ("commentsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_194ef33aa9b7f19efb9b1656a6" ON "comments_liked_by_users_users" ("usersId") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_194ef33aa9b7f19efb9b1656a6"`);
        await queryRunner.query(`DROP INDEX "IDX_d00c912f2d8aa0284a58425217"`);
        await queryRunner.query(`ALTER TABLE "comments_liked_by_users_users" RENAME TO "temporary_comments_liked_by_users_users"`);
        await queryRunner.query(`CREATE TABLE "comments_liked_by_users_users" ("commentsId" integer NOT NULL, "usersId" integer NOT NULL, PRIMARY KEY ("commentsId", "usersId"))`);
        await queryRunner.query(`INSERT INTO "comments_liked_by_users_users"("commentsId", "usersId") SELECT "commentsId", "usersId" FROM "temporary_comments_liked_by_users_users"`);
        await queryRunner.query(`DROP TABLE "temporary_comments_liked_by_users_users"`);
        await queryRunner.query(`CREATE INDEX "IDX_194ef33aa9b7f19efb9b1656a6" ON "comments_liked_by_users_users" ("usersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d00c912f2d8aa0284a58425217" ON "comments_liked_by_users_users" ("commentsId") `);
        await queryRunner.query(`DROP INDEX "IDX_92925b1bdd372ce994c9e94eb4"`);
        await queryRunner.query(`DROP INDEX "IDX_719f65dd281f090dc50af6d1de"`);
        await queryRunner.query(`ALTER TABLE "tweets_saved_by_users_users" RENAME TO "temporary_tweets_saved_by_users_users"`);
        await queryRunner.query(`CREATE TABLE "tweets_saved_by_users_users" ("tweetsId" integer NOT NULL, "usersId" integer NOT NULL, PRIMARY KEY ("tweetsId", "usersId"))`);
        await queryRunner.query(`INSERT INTO "tweets_saved_by_users_users"("tweetsId", "usersId") SELECT "tweetsId", "usersId" FROM "temporary_tweets_saved_by_users_users"`);
        await queryRunner.query(`DROP TABLE "temporary_tweets_saved_by_users_users"`);
        await queryRunner.query(`CREATE INDEX "IDX_92925b1bdd372ce994c9e94eb4" ON "tweets_saved_by_users_users" ("usersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_719f65dd281f090dc50af6d1de" ON "tweets_saved_by_users_users" ("tweetsId") `);
        await queryRunner.query(`DROP INDEX "IDX_e28f0beac1581abaefce32d51b"`);
        await queryRunner.query(`DROP INDEX "IDX_a2b4a8e105439cac45a404c97c"`);
        await queryRunner.query(`ALTER TABLE "tweets_favorited_by_users_users" RENAME TO "temporary_tweets_favorited_by_users_users"`);
        await queryRunner.query(`CREATE TABLE "tweets_favorited_by_users_users" ("tweetsId" integer NOT NULL, "usersId" integer NOT NULL, PRIMARY KEY ("tweetsId", "usersId"))`);
        await queryRunner.query(`INSERT INTO "tweets_favorited_by_users_users"("tweetsId", "usersId") SELECT "tweetsId", "usersId" FROM "temporary_tweets_favorited_by_users_users"`);
        await queryRunner.query(`DROP TABLE "temporary_tweets_favorited_by_users_users"`);
        await queryRunner.query(`CREATE INDEX "IDX_e28f0beac1581abaefce32d51b" ON "tweets_favorited_by_users_users" ("usersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a2b4a8e105439cac45a404c97c" ON "tweets_favorited_by_users_users" ("tweetsId") `);
        await queryRunner.query(`DROP INDEX "IDX_b8bc26740590d4a2740a8c29e2"`);
        await queryRunner.query(`DROP INDEX "IDX_946e8168d267545ce143b93a31"`);
        await queryRunner.query(`ALTER TABLE "hashtags_tweets_tweets" RENAME TO "temporary_hashtags_tweets_tweets"`);
        await queryRunner.query(`CREATE TABLE "hashtags_tweets_tweets" ("hashtagsId" integer NOT NULL, "tweetsId" integer NOT NULL, PRIMARY KEY ("hashtagsId", "tweetsId"))`);
        await queryRunner.query(`INSERT INTO "hashtags_tweets_tweets"("hashtagsId", "tweetsId") SELECT "hashtagsId", "tweetsId" FROM "temporary_hashtags_tweets_tweets"`);
        await queryRunner.query(`DROP TABLE "temporary_hashtags_tweets_tweets"`);
        await queryRunner.query(`CREATE INDEX "IDX_b8bc26740590d4a2740a8c29e2" ON "hashtags_tweets_tweets" ("tweetsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_946e8168d267545ce143b93a31" ON "hashtags_tweets_tweets" ("hashtagsId") `);
        await queryRunner.query(`DROP INDEX "IDX_1433e3275a501bc09f5c33c7ca"`);
        await queryRunner.query(`DROP INDEX "IDX_8d63f6043394b4d32343bdea11"`);
        await queryRunner.query(`ALTER TABLE "users_followers_users" RENAME TO "temporary_users_followers_users"`);
        await queryRunner.query(`CREATE TABLE "users_followers_users" ("usersId_1" integer NOT NULL, "usersId_2" integer NOT NULL, PRIMARY KEY ("usersId_1", "usersId_2"))`);
        await queryRunner.query(`INSERT INTO "users_followers_users"("usersId_1", "usersId_2") SELECT "usersId_1", "usersId_2" FROM "temporary_users_followers_users"`);
        await queryRunner.query(`DROP TABLE "temporary_users_followers_users"`);
        await queryRunner.query(`CREATE INDEX "IDX_1433e3275a501bc09f5c33c7ca" ON "users_followers_users" ("usersId_2") `);
        await queryRunner.query(`CREATE INDEX "IDX_8d63f6043394b4d32343bdea11" ON "users_followers_users" ("usersId_1") `);
        await queryRunner.query(`DROP INDEX "IDX_61882bbc479c68d6d8e78cd4fc"`);
        await queryRunner.query(`DROP INDEX "IDX_73b033036fce7837ab92be3372"`);
        await queryRunner.query(`ALTER TABLE "users_retweets_tweets" RENAME TO "temporary_users_retweets_tweets"`);
        await queryRunner.query(`CREATE TABLE "users_retweets_tweets" ("usersId" integer NOT NULL, "tweetsId" integer NOT NULL, PRIMARY KEY ("usersId", "tweetsId"))`);
        await queryRunner.query(`INSERT INTO "users_retweets_tweets"("usersId", "tweetsId") SELECT "usersId", "tweetsId" FROM "temporary_users_retweets_tweets"`);
        await queryRunner.query(`DROP TABLE "temporary_users_retweets_tweets"`);
        await queryRunner.query(`CREATE INDEX "IDX_61882bbc479c68d6d8e78cd4fc" ON "users_retweets_tweets" ("tweetsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_73b033036fce7837ab92be3372" ON "users_retweets_tweets" ("usersId") `);
        await queryRunner.query(`ALTER TABLE "comments" RENAME TO "temporary_comments"`);
        await queryRunner.query(`CREATE TABLE "comments" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "text" varchar NOT NULL, "image" varchar NOT NULL DEFAULT (''), "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "author_id" integer NOT NULL, "tweet_id" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "comments"("id", "text", "image", "created_at", "author_id", "tweet_id") SELECT "id", "text", "image", "created_at", "author_id", "tweet_id" FROM "temporary_comments"`);
        await queryRunner.query(`DROP TABLE "temporary_comments"`);
        await queryRunner.query(`ALTER TABLE "tweets" RENAME TO "temporary_tweets"`);
        await queryRunner.query(`CREATE TABLE "tweets" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "text" varchar(280) NOT NULL, "image" varchar NOT NULL DEFAULT (''), "commentAllowed" varchar NOT NULL DEFAULT ('everyone'), "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "author_id" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "tweets"("id", "text", "image", "commentAllowed", "created_at", "author_id") SELECT "id", "text", "image", "commentAllowed", "created_at", "author_id" FROM "temporary_tweets"`);
        await queryRunner.query(`DROP TABLE "temporary_tweets"`);
        await queryRunner.query(`DROP INDEX "IDX_194ef33aa9b7f19efb9b1656a6"`);
        await queryRunner.query(`DROP INDEX "IDX_d00c912f2d8aa0284a58425217"`);
        await queryRunner.query(`DROP TABLE "comments_liked_by_users_users"`);
        await queryRunner.query(`DROP INDEX "IDX_92925b1bdd372ce994c9e94eb4"`);
        await queryRunner.query(`DROP INDEX "IDX_719f65dd281f090dc50af6d1de"`);
        await queryRunner.query(`DROP TABLE "tweets_saved_by_users_users"`);
        await queryRunner.query(`DROP INDEX "IDX_e28f0beac1581abaefce32d51b"`);
        await queryRunner.query(`DROP INDEX "IDX_a2b4a8e105439cac45a404c97c"`);
        await queryRunner.query(`DROP TABLE "tweets_favorited_by_users_users"`);
        await queryRunner.query(`DROP INDEX "IDX_b8bc26740590d4a2740a8c29e2"`);
        await queryRunner.query(`DROP INDEX "IDX_946e8168d267545ce143b93a31"`);
        await queryRunner.query(`DROP TABLE "hashtags_tweets_tweets"`);
        await queryRunner.query(`DROP INDEX "IDX_1433e3275a501bc09f5c33c7ca"`);
        await queryRunner.query(`DROP INDEX "IDX_8d63f6043394b4d32343bdea11"`);
        await queryRunner.query(`DROP TABLE "users_followers_users"`);
        await queryRunner.query(`DROP INDEX "IDX_61882bbc479c68d6d8e78cd4fc"`);
        await queryRunner.query(`DROP INDEX "IDX_73b033036fce7837ab92be3372"`);
        await queryRunner.query(`DROP TABLE "users_retweets_tweets"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP TABLE "tweets"`);
        await queryRunner.query(`DROP TABLE "hashtags"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
